name: Keep Streamlit App Alive

on:
  schedule:
    # Berjalan setiap 12 jam (jangan terlalu sering agar tidak diblokir GitHub)
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        # Ganti URL di bawah dengan URL aplikasi Streamlit Anda
        run: curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -L "https://nama-aplikasi-anda.streamlit.app"
