name: Keep Streamlit App Awake

on:
  schedule:
    # Berjalan otomatis setiap 3 hari sekali pada jam 00:00 UTC
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Memungkinkan tombol 'Run workflow' manual di GitHub Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -I "https://bagussdaab4.streamlit.app/" | head -n 1
